name = "me-cli-worker"
# jika kamu build sendiri:
main = "dist/index.js"
# atau biarkan Wrangler bundling TS:
# main = "src/index.ts"

compatibility_date = "2025-09-25"

[vars]
BASE_API_URL  = "https://api.myxl.xlaxiata.co.id"
BASE_CIAM_URL = "https://gede.ciam.xlaxiata.co.id"
CRYPTO_API    = "https://crypto.mashu.lol/api/870"
UA            = "okhttp/5.0 (Android 13; ...)"

[observability]
enabled = true
